### ISSUE TITLE
Create temp file in the same directory where output supposed to be put

### ISSUE THREAD

**Issue by kad** [intel/bmap-tools#31]
Right now temporary file created in the directory of image, which might be not-writable.

```console
kad@kad:/mnt/5/ttt> bmaptool create -o ./1.bmap ../tt/sample-x86_64.iso 
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/kad/bin/bmaptool/__main__.py", line 11, in <module>
  File "/home/kad/bin/bmaptool/bmaptools/CLI.py", line 715, in main
  File "/home/kad/bin/bmaptool/bmaptools/CLI.py", line 548, in create_command
  File "/home/kad/bin/bmaptool/bmaptools/BmapCreate.py", line 176, in __init__
  File "/home/kad/bin/bmaptool/bmaptools/Filemap.py", line 525, in filemap
  File "/home/kad/bin/bmaptool/bmaptools/Filemap.py", line 202, in __init__
  File "/home/kad/bin/bmaptool/bmaptools/Filemap.py", line 221, in _probe_seek_hole
  File "/usr/lib64/python2.7/tempfile.py", line 511, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib64/python2.7/tempfile.py", line 244, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '../tt/tmpkYrxDs'
kad@kad:/mnt/5/ttt> 
```

**Comment by lurch** [comment]
https://github.com/intel/bmap-tools/blob/master/bmaptools/Filemap.py#L205 says:
> I could not invent a better way of detecting the fake 'SEEK_HOLE'
implementation than just to create a temporary file in the same
directory where the image file resides. It would be nice to change this
to something better.

So I dunno if there's an easy workaround (in more detail: the code checks if SEEK_HOLE works by deliberately creating a file with a hole in it, and seeing if SEEK_HOLE finds it).
Obviously if the temporary file was created in the same directory as the output file, then that'd tell you if the filesystem that the output file is on supported SEEK_HOLE, but it doesn't tell you if the filesystem that the original image is on supports SEEK_HOLE.

Also, I noticed the code does:
```python
        try:
            tmp_obj = tempfile.TemporaryFile("w+", dir=directory)
        except IOError as err:
            raise ErrorNotSupp("cannot create a temporary in \"%s\": %s"
                               % (directory, err))
```
which means you theoretically ought to be seeing a different error than the stacktrace you've got above.

In a Python2 REPL I get:
```python
Python 2.7.6 (default, Nov 23 2017, 15:49:48) 
[GCC 4.8.4] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> t = tempfile.TemporaryFile(dir='/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/tempfile.py", line 493, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python2.7/tempfile.py", line 239, in _mkstemp_inner
    fd = _os.open(file, flags, 0600)
OSError: [Errno 13] Permission denied: '/tmpNHSV0B'
```
and in a Python3 REPL I get:
```python
Python 3.4.3 (default, Nov 28 2017, 16:41:13) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tempfile
>>> t = tempfile.TemporaryFile(dir='/')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.4/tempfile.py", line 636, in TemporaryFile
    (fd, name) = _mkstemp_inner(dir, prefix, suffix, flags)
  File "/usr/lib/python3.4/tempfile.py", line 339, in _mkstemp_inner
    fd = _os.open(file, flags, 0o600)
PermissionError: [Errno 13] Permission denied: '/tmp9jlebdok'
```

In Python3 `PermissionError` is a [child](https://docs.python.org/3/library/exceptions.html#exception-hierarchy) of `OSError` so I wonder if the `except IOError as err:` [here](https://github.com/intel/bmap-tools/blob/master/bmaptools/Filemap.py#L223) is _actually_ supposed to be `except OSError as err:` ?

**Comment by dedekind** [comment]
Feel free to suggest patches.

**Comment by lurch** [comment]
@kad Do you want to test the latest `master`, to see if #39 fixes the problem (or at least gives you a better error message) ?

**Comment by dedekind** [comment]
Hello, the project was moved and now owned by a new team. Please, work with them. Check the README.md file. Thanks!
