### ISSUE TITLE
copy from http url doesn't work

### ISSUE THREAD

**Issue by dimtass** [intel/bmap-tools#50]
I'm using bmaptool 3.4.

There's an issue with fetching bmap'ed images from http. The first error is that when
you try to use bmaptool with http like this:
`bmaptool copy http://link.to/file.wic /dev/sdX`

then I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/bmaptool", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 715, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 423, in copy_command
    open_files(args)
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 365, in open_files
    (bmap_obj, bmap_path) = find_and_open_bmap(args)
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 335, in find_and_open_bmap
    shutil.copyfileobj(bmap_obj, tmp_obj)
  File "/usr/lib/python3.6/shutil.py", line 82, in copyfileobj
    fdst.write(buf)
  File "/usr/lib/python3.6/tempfile.py", line 622, in func_wrapper
    return func(*args, **kwargs)
TypeError: write() argument must be str, not bytes
```

This can be fixed in `CLI.py` in line #330 by replacing
```
tmp_obj = tempfile.NamedTemporaryFile("w+")
```
with
```
tmp_obj = tempfile.NamedTemporaryFile("wb+")
```

After this it does find the URL as also the bmap file in the http server, but then
I get this error:
```
Traceback (most recent call last):
  File "/usr/bin/bmaptool", line 11, in <module>
    sys.exit(main())
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 715, in main
    args.func(args)
  File "/usr/lib/python3/dist-packages/bmaptools/CLI.py", line 477, in copy_command
    writer.copy(False, not args.no_verify)
  File "/usr/lib/python3/dist-packages/bmaptools/BmapCopy.py", line 791, in copy
    BmapCopy.copy(self, sync, verify)
  File "/usr/lib/python3/dist-packages/bmaptools/BmapCopy.py", line 584, in copy
    raise exc_info[1].with_traceback(exc_info[2])
  File "/usr/lib/python3/dist-packages/bmaptools/BmapCopy.py", line 503, in _get_data
    self._f_image.seek(first * self.block_size)
  File "/usr/lib/python3/dist-packages/bmaptools/TransRead.py", line 587, in seek
    self._f_objs[-1].seek(offset, whence)
io.UnsupportedOperation: seek
```

This seems to come from `TransRead.py`, but there I'm lost...

Any ideas?
Thanks!

**Comment by dimtass** [comment]
Sorry, I found that it's resolved in the git master branch and ubuntu, yocto e.t.c. they just use older versions!

**Comment by smcv** [comment]
This is basically [Debian bug 896182](https://bugs.debian.org/896182), which is fixed in bmap-tools Debian package version 3.4-2.

> This can be fixed in CLI.py in line #330 by replacing
>
>     tmp_obj = tempfile.NamedTemporaryFile("w+")
>
> with
>
>     tmp_obj = tempfile.NamedTemporaryFile("wb+")

That was fixed by #47

> `io.UnsupportedOperation: seek`

That was fixed by #46

**Comment by dedekind** [comment]
I guess we need to make another release.

**Comment by dimtass** [comment]
That would be great. I've tested http copy my self thoroughly and it seems to be robust with small and rather big wic images.
